image: docker:stable

services:
  - docker:dind

before_script:
  - docker info

build:
  only:
    - master
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - 'docker build -t localhost:5050/lanstaller/lanstaller .'
    
deploy:
  stage: deploy
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script: 
    - 'docker push localhost:5050/lanstaller/lanstaller'
  
  only:
    - master
