image: docker:stable

variables:
  DOCKER_HOST: tcp://172.17.0.1:2375/
  DOCKER_DRIVER: overlay2



build_api:
  only:
    - master
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - 'docker build -t gitlab.yden.au:5050/lanstaller/lanstaller/api -f LanstallerAPI/Dockerfile .'
  parallel:
    matrix:
      - PROJECT: api
    
deploy_api:
  stage: deploy
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script: 
    - 'docker push gitlab.yden.au:5050/lanstaller/lanstaller/api'
  parallel:
    matrix:
      - PROJECT: api
  only:
    - master

build_web:
  only:
      - master
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - 'docker build -t gitlab.yden.au:5050/lanstaller/lanstaller/web -f LanstallerWeb/Dockerfile .'
  parallel:
    matrix:
      - PROJECT: web
      
    
deploy_web:
  stage: deploy
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script: 
    - 'docker push gitlab.yden.au:5050/lanstaller/lanstaller/web'
  parallel:
    matrix:
      - PROJECT: web
  