image: docker:stable

services:
  - docker:dind

before_script:
  - docker info

build_api:
  only:
    - master
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - 'docker build -t gitlab.mrhsystems.com:5050/lanstaller/lanstaller/api -f LanstallerAPI/Dockerfile .'
  parallel:
    matrix:
      - PROJECT: api
    
deploy_api:
  stage: deploy
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script: 
    - 'docker push gitlab.mrhsystems.com:5050/lanstaller/lanstaller/api'
  parallel:
    matrix:
      - PROJECT: api
  only:
    - master

build_web:
  only:
      - master
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - 'docker build -t gitlab.mrhsystems.com:5050/lanstaller/lanstaller/web -f LanstallerWeb/Dockerfile .'
  parallel:
    matrix:
      - PROJECT: web
      
    
deploy_web:
  stage: deploy
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script: 
    - 'docker push gitlab.mrhsystems.com:5050/lanstaller/lanstaller/web'
  parallel:
    matrix:
      - PROJECT: web
  